package posting

// Viloyat -> tuman ro'yxati. MANBA: apps/web/lib/regions.ts
// (u esa flutter-app/lib/core/constants/uz_regions.dart bilan bir xil).
//
// NEGA NUSXA: bot alohida Go moduli va veb kodini import qila olmaydi.
// Nomlar AYNAN bir xil bo'lishi SHART — profil maydoniga shu satrlar
// yoziladi va sayt, mobil ilova hamda bot bitta hisobni ko'radi. Manba
// ro'yxati o'zgarsa shu fayl ham qayta hosil qilinishi kerak.
//
// Nomlarda odatdagi apostrof emas, U+02BB (ʻ) ishlatiladi — manbadagidek.

type regionDistricts struct {
	Name      string
	Districts []string
}

var uzRegions = []regionDistricts{
	{"Toshkent shahri", []string{
		"Bektemir tumani",
		"Chilonzor tumani",
		"Mirobod tumani",
		"Mirzo Ulugʻbek tumani",
		"Olmazor tumani",
		"Sergeli tumani",
		"Shayxontohur tumani",
		"Uchtepa tumani",
		"Yakkasaroy tumani",
		"Yangihayot tumani",
		"Yashnobod tumani",
		"Yunusobod tumani",
	}},
	{"Toshkent viloyati", []string{
		"Bekobod tumani",
		"Boʻka tumani",
		"Boʻstonliq tumani",
		"Chinoz tumani",
		"Ohangaron tumani",
		"Oqqoʻrgʻon tumani",
		"Oʻrta Chirchiq tumani",
		"Parkent tumani",
		"Piskent tumani",
		"Qibray tumani",
		"Quyi Chirchiq tumani",
		"Toshkent tumani",
		"Yangiyoʻl tumani",
		"Yuqori Chirchiq tumani",
		"Zangiota tumani",
		"Angren shahri",
		"Bekobod shahri",
		"Chirchiq shahri",
		"Nurafshon shahri",
		"Ohangaron shahri",
		"Olmaliq shahri",
		"Yangiyoʻl shahri",
	}},
	{"Samarqand", []string{
		"Bulungʻur tumani",
		"Ishtixon tumani",
		"Jomboy tumani",
		"Kattaqoʻrgʻon tumani",
		"Narpay tumani",
		"Nurobod tumani",
		"Oqdaryo tumani",
		"Pastdargʻom tumani",
		"Paxtachi tumani",
		"Payariq tumani",
		"Qoʻshrabot tumani",
		"Samarqand tumani",
		"Toyloq tumani",
		"Urgut tumani",
		"Kattaqoʻrgʻon shahri",
		"Samarqand shahri",
	}},
	{"Andijon", []string{
		"Andijon tumani",
		"Asaka tumani",
		"Baliqchi tumani",
		"Boʻston tumani",
		"Buloqboshi tumani",
		"Izboskan tumani",
		"Jalaquduq tumani",
		"Marhamat tumani",
		"Oltinkoʻl tumani",
		"Paxtaobod tumani",
		"Qoʻrgʻontepa tumani",
		"Shahrixon tumani",
		"Ulugʻnor tumani",
		"Xoʻjaobod tumani",
		"Andijon shahri",
		"Xonobod shahri",
	}},
	{"Fargʻona", []string{
		"Bagʻdod tumani",
		"Beshariq tumani",
		"Buvayda tumani",
		"Dangʻara tumani",
		"Fargʻona tumani",
		"Furqat tumani",
		"Oltiariq tumani",
		"Oʻzbekiston tumani",
		"Qoʻshtepa tumani",
		"Quva tumani",
		"Rishton tumani",
		"Soʻx tumani",
		"Toshloq tumani",
		"Uchkoʻprik tumani",
		"Yozyovon tumani",
		"Fargʻona shahri",
		"Margʻilon shahri",
		"Qoʻqon shahri",
		"Quvasoy shahri",
	}},
	{"Namangan", []string{
		"Chortoq tumani",
		"Chust tumani",
		"Kosonsoy tumani",
		"Mingbuloq tumani",
		"Namangan tumani",
		"Norin tumani",
		"Pop tumani",
		"Toʻraqoʻrgʻon tumani",
		"Uchqoʻrgʻon tumani",
		"Uychi tumani",
		"Yangiqoʻrgʻon tumani",
		"Namangan shahri",
	}},
	{"Buxoro", []string{
		"Buxoro tumani",
		"Gʻijduvon tumani",
		"Jondor tumani",
		"Kogon tumani",
		"Olot tumani",
		"Peshku tumani",
		"Qorakoʻl tumani",
		"Qorovulbozor tumani",
		"Romitan tumani",
		"Shofirkon tumani",
		"Vobkent tumani",
		"Buxoro shahri",
		"Kogon shahri",
	}},
	{"Qashqadaryo", []string{
		"Chiroqchi tumani",
		"Dehqonobod tumani",
		"Gʻuzor tumani",
		"Kasbi tumani",
		"Kitob tumani",
		"Koson tumani",
		"Koʻkdala tumani",
		"Mirishkor tumani",
		"Muborak tumani",
		"Nishon tumani",
		"Qamashi tumani",
		"Qarshi tumani",
		"Shahrisabz tumani",
		"Yakkabogʻ tumani",
		"Qarshi shahri",
		"Shahrisabz shahri",
	}},
	{"Surxondaryo", []string{
		"Angor tumani",
		"Bandixon tumani",
		"Boysun tumani",
		"Denov tumani",
		"Jarqoʻrgʻon tumani",
		"Muzrabot tumani",
		"Oltinsoy tumani",
		"Qiziriq tumani",
		"Qumqoʻrgʻon tumani",
		"Sariosiyo tumani",
		"Sherobod tumani",
		"Shoʻrchi tumani",
		"Termiz tumani",
		"Uzun tumani",
		"Termiz shahri",
	}},
	{"Xorazm", []string{
		"Bogʻot tumani",
		"Gurlan tumani",
		"Hazorasp tumani",
		"Qoʻshkoʻpir tumani",
		"Shovot tumani",
		"Tuproqqalʻa tumani",
		"Urganch tumani",
		"Xiva tumani",
		"Xonqa tumani",
		"Yangiariq tumani",
		"Yangibozor tumani",
		"Urganch shahri",
		"Xiva shahri",
	}},
	{"Navoiy", []string{
		"Karmana tumani",
		"Konimex tumani",
		"Navbahor tumani",
		"Nurota tumani",
		"Qiziltepa tumani",
		"Tomdi tumani",
		"Uchquduq tumani",
		"Xatirchi tumani",
		"Gʻozgʻon shahri",
		"Navoiy shahri",
		"Zarafshon shahri",
	}},
	{"Jizzax", []string{
		"Arnasoy tumani",
		"Baxmal tumani",
		"Doʻstlik tumani",
		"Forish tumani",
		"Gʻallaorol tumani",
		"Jizzax tumani",
		"Mirzachoʻl tumani",
		"Paxtakor tumani",
		"Yangiobod tumani",
		"Zafarobod tumani",
		"Zarbdor tumani",
		"Zomin tumani",
		"Jizzax shahri",
	}},
	{"Sirdaryo", []string{
		"Boyovut tumani",
		"Guliston tumani",
		"Mirzaobod tumani",
		"Oqoltin tumani",
		"Sardoba tumani",
		"Sayxunobod tumani",
		"Sirdaryo tumani",
		"Xovos tumani",
		"Guliston shahri",
		"Shirin shahri",
		"Yangiyer shahri",
	}},
	{"Qoraqalpogʻiston", []string{
		"Amudaryo tumani",
		"Beruniy tumani",
		"Boʻzatov tumani",
		"Chimboy tumani",
		"Ellikqalʻa tumani",
		"Kegeyli tumani",
		"Moʻynoq tumani",
		"Nukus tumani",
		"Qanlikoʻl tumani",
		"Qoraoʻzak tumani",
		"Qoʻngʻirot tumani",
		"Shumanay tumani",
		"Taxtakoʻpir tumani",
		"Taxiatosh tumani",
		"Toʻrtkoʻl tumani",
		"Xoʻjayli tumani",
		"Nukus shahri",
	}},
}
